- src/app/app.module.ts
- src/app/service/router.service.ts
- src/app/service/trace.service.ts
- src/app/shared/pipe/title-case.pipe.ts
- src/app/shared/shared.module.ts
- src/app/views/detail/session/main/detail-session-main.view.html
- src/app/views/detail/session/main/detail-session-main.view.ts
- src/app/views/detail/session/rest/detail-session-rest.view.html
- src/app/views/detail/session/rest/detail-session-rest.view.ts
- src/app/views/dump/dump.view.html
- src/app/views/dump/dump.view.scss
- src/app/views/dump/dump.view.ts
- src/app/views/dump/timeline/dump-timeline.component.ts
- src/app/views/views.module.ts
> screen to view Processes (sessions) running on a server for a specific duration

- src/app/app.module.ts
- src/app/shared/material/custom-date-adapter.ts
- src/app/shared/material/custom-date-range-selection-strategy.ts
- src/app/shared/material/material.module.ts
- src/app/shared/shared.module.ts
- src/app/views/architecture/architecture.view.ts
- src/app/views/dashboard/dashboard.component.ts
- src/app/views/search/main/search-main.view.html
- src/app/views/search/main/search-main.view.ts
- src/app/views/search/rest/search-rest.view.html
- src/app/views/search/rest/search-rest.view.ts
- src/app/views/statistic/application/statistic-application.view.ts
- src/app/views/statistic/database/statistic-database.view.ts
- src/app/views/statistic/rest/statistic-rest.view.ts
- src/app/views/statistic/user/statistic-user.view.ts
- src/app/views/statistic/view/statistic-client.view.ts
- src/environments/environment.ts
- src/styles.scss
> DateTimePicker on search session view for lower data

- src/app/model/trace.model.ts
- src/app/shared/pipe/duration.pipe.ts
- src/app/views/detail/session/_component/database-table/detail-database-table.component.html
- src/app/views/detail/session/_component/ftp-table/detail-ftp-table.component.html
- src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.html
- src/app/views/detail/session/_component/local-table/detail-local-table.component.html
- src/app/views/detail/session/_component/rest-table/detail-rest-table.component.html
- src/app/views/detail/session/_component/smtp-table/detail-smtp-table.component.html
- src/app/views/detail/session/_component/timeline/detail-timeline.component.ts
- src/app/views/detail/session/rest/detail-session-rest.view.ts
- src/styles.scss
- Fixed timeline graph no showing due to requests not having end value
- Replaced null end values showed detail subrequest tables
- Fixed tooltip message not breaking line 
- Replaced null end values showed tree view
> [Bug] Fixed view bugs related to end value being null

- src/app/views/detail/session/_component/detail-session.component.html
- src/app/views/detail/session/_component/detail-session.component.ts
- src/app/views/detail/session/rest/detail-session-rest.view.html
- src/app/views/detail/session/rest/detail-session-rest.view.ts
changes :
- cards are loaded independently as soon as data is received 
- added a loading indicator when getting the parent of session 
- added a loafing indicator when getting db info in instance cards
additional changes: 
- fixed a bug where parent session is not set to default after navigation 
- fixed a bug where db info showed in instance card is not set to default after navigation
- clean consoles / unused imports
> Fix: [inspect-app#67] resolve multiple bugs related to loading in detail session page

- src/app/model/conf.model.ts
- src/app/service/router.service.ts
- src/app/shared/material/custom-date-adapter.ts
- src/app/views/search/main/search-main.view.html
- src/app/views/search/main/search-main.view.ts
- src/app/views/search/rest/search-rest.view.html
- src/app/views/search/rest/search-rest.view.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
changes: #66
- Clean console 
- Date is no longer shown when we have step
- Simplified code (QueryParam with modelisation)
- Fixed regex DateTimePicker
> Fixed bugs related to range DateTimePicker

- src/app/views/detail/session/_component/detail-session.component.html
- src/app/views/detail/session/_component/timeline/detail-timeline.component.html
- src/app/views/detail/session/_component/timeline/detail-timeline.component.ts
- src/styles.scss
fix: #91 
- Data is set dynamically when the session has more than 50 elements.
- For sessions with more than 50 elements, an initial zoom is applied to display only the first 50 elements.
- A legend has been added above the timeline graph.
> Improved timeline component

- src/app/model/conf.model.ts
- src/app/shared/util.ts
- src/app/views/search/main/search-main.view.ts
- src/app/views/search/rest/search-rest.view.ts
- src/environments/environment.ts
> Enhanced the configuration used in the app

- angular.json
- src/environments/environment.prod.ts
- src/environments/environment.ts
> Fixed uncorrect configuration when building in production env 

- src/app/model/tree.model.ts
> Added a dedicated icon for batch nodes in tree view

- README.md
> Added documentation for all application constants in README.md

- angular.json
- src/app/shared/pipe/exception-type.pipe.ts
- src/app/shared/pipe/trunc-string.pipe.ts
- src/app/shared/shared.module.ts
- src/app/views/detail/session/_component/local-table/detail-local-table.component.html
- src/app/views/detail/session/_component/rest-table/detail-rest-table.component.html
- src/app/views/search/main/search-main.view.html
- src/app/views/search/main/search-main.view.ts
- src/app/views/search/rest/search-rest.view.html
- src/app/views/search/rest/search-rest.view.scss
- src/app/views/search/rest/search-rest.view.ts
- src/styles.scss
Display type and message exception on a tooltip 
- Search session view 
- Detail session view (Rest Request and Local Request)
closes: [#81](https://github.com/oneteme/inspect-app/issues/81)
> Display exception on table

- src/app/views/detail/database/detail-database.view.html
- src/app/views/detail/database/detail-database.view.ts
- src/app/views/detail/session/main/detail-session-main.view.html
- src/app/views/detail/session/rest/detail-session-rest.view.html
closes : #114 
additional changes: 
- added branch and hash informations to instance card 
- removed db info from instance card, db statistiques can be accessed from db request detail
- changed the placement of the stage count in db request detail timeline
> improved Session detail view  

- src/app/app.component.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
> update environment files for local,prd

- src/app/views/detail/session/_component/database-table/detail-database-table.component.html
> show schema instead of name when schema is not null

- src/app/views/detail/session/_component/database-table/detail-database-table.component.html
- src/app/views/detail/session/_component/timeline/detail-timeline.component.ts
> show schema if null instead of database in session detail view

- src/app/views/detail/session/_component/database-table/detail-database-table.component.ts
- src/app/views/detail/session/_component/ftp-table/detail-ftp-table.component.ts
- src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.ts
- src/app/views/detail/session/_component/local-table/detail-local-table.component.ts
- src/app/views/detail/session/_component/rest-table/detail-rest-table.component.ts
- src/app/views/detail/session/_component/smtp-table/detail-smtp-table.component.ts
> Order by durre not working  in session-detail 

- src/app/shared/pipe/number.pipe.ts
- src/app/views/detail/session/_component/detail-session.component.html
- src/app/views/views.module.ts
- src/styles.scss
> Improve badge visual 

- src/app/shared/util.ts
- src/app/views/detail/database/detail-database.view.ts
- src/app/views/detail/ftp/detail-ftp.view.ts
- src/app/views/detail/ldap/detail-ldap.view.ts
- src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.ts
- src/app/views/detail/smtp/detail-smtp.view.ts
- src/styles.scss
closes : #124 
additional changes: 
- correctly show timeline if stage end is null 
- correctly show err  when stages has exception 
- fixed zoom start and end to show all elements in timeline
> Show main request  in stages detail  

- src/app/app.component.html
- src/app/app.module.ts
- src/app/model/jquery.model.ts
- src/app/service/jquery/instance.service.ts
- src/app/views/constants.ts
- src/app/views/deploiment/deploiment.component.html
- src/app/views/deploiment/deploiment.component.scss
- src/app/views/deploiment/deploiment.component.ts
- src/app/views/views.module.ts
- src/styles.scss
> Deployment view 

- src/app/model/trace.model.ts
- src/app/views/detail/session/rest/detail-session-rest.view.html
> Show instance duration on session detail

- src/app/model/trace.model.ts
- src/app/model/tree.model.ts
- src/app/shared/_component/advanced-filter/advanced-filter-trigger/advanced-filter-trigger.component.ts
- src/app/views/tree/tree.view.ts
> Show request exception instead of session exception in tree's links

- src/app/shared/_component/advanced-filter/advanced-filter-trigger/advanced-filter-trigger.component.ts
- src/app/views/architecture/architecture.view.ts
- src/app/views/dashboard/dashboard.component.ts
- src/app/views/deploiment/deploiment.component.ts
- src/app/views/detail/session/main/detail-session-main.view.ts
- src/app/views/detail/session/rest/detail-session-rest.view.ts
- src/app/views/search/main/search-main.view.ts
- src/app/views/search/rest/search-rest.view.ts
- src/app/views/statistic/application/statistic-application.view.ts
- src/app/views/statistic/database/statistic-database.view.ts
- src/app/views/statistic/rest/statistic-rest.view.ts
- src/app/views/statistic/user/statistic-user.view.ts
- src/app/views/statistic/view/statistic-client.view.ts
- src/app/views/tree/tree.view.ts
> Clear requests when URL changes

- src/main.ts
> rename assets/environment file in main.ts

- src/app/app.component.ts
- src/app/views/architecture/architecture.view.ts
- src/app/views/dashboard/dashboard.component.ts
- src/app/views/detail/database/detail-database.view.ts
- src/app/views/detail/ftp/detail-ftp.view.ts
- src/app/views/detail/ldap/detail-ldap.view.ts
- src/app/views/detail/session/main/detail-session-main.view.ts
- src/app/views/detail/session/rest/detail-session-rest.view.ts
- src/app/views/detail/smtp/detail-smtp.view.ts
- src/app/views/statistic/application/statistic-application.view.ts
- src/app/views/statistic/database/statistic-database.view.ts
- src/app/views/statistic/rest/statistic-rest.view.ts
- src/app/views/statistic/user/statistic-user.view.ts
- src/app/views/statistic/view/statistic-client.view.ts
- src/app/views/tree/tree.view.ts
- src/main.ts
> Used new environment config for defaultEnv

- src/app/app.component.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
> correctly set server url in localstorage

- src/app/views/detail/session/_component/detail-session.component.html
> set badge show condition correctly

- src/app/app.component.html
- src/app/views/constants.ts
- src/app/views/deploiment/deploiment.component.html
- src/app/views/deploiment/deploiment.component.ts
- src/app/views/detail/database/detail-database.view.ts
- src/app/views/detail/ftp/detail-ftp.view.ts
- src/app/views/detail/ldap/detail-ldap.view.ts
- src/app/views/detail/session/_component/timeline/detail-timeline.component.html
- src/app/views/detail/smtp/detail-smtp.view.ts
- src/styles.scss
closes : #162
- changed the placement of deploiment view button 
- removed collector from deploiment view 
- fix bug in bdd,ldap,smtp and ftp detail where duration is negative
> bug fixes 

- package.json
- src/app/app.component.html
- src/app/service/jquery/instance.service.ts
- src/app/views/constants.ts
- src/app/views/detail/session/main/detail-session-main.view.html
- src/app/views/detail/session/rest/detail-session-rest.view.html
> inspect-app 1.0

- src/app/views/statistic/server/_component/batch-tab/_component/repartition-type-card/repartition-type-card.component.ts
- src/app/views/statistic/server/_component/evol-user-card/evol-user-card.component.ts
- src/app/views/statistic/server/_component/performance-card/performance-card.component.ts
- src/app/views/statistic/server/_component/rest-tab/_component/repartition-type-card/repartition-type-card.component.ts
> hotfix dist jquery core

- README.md
> 178 doc inspect app

- src/app/service/jquery/database-request.service.ts
- src/app/service/jquery/ftp-request.service.ts
- src/app/service/jquery/ldap-request.service.ts
- src/app/service/jquery/rest-request.service.ts
- src/app/service/jquery/smtp-request.service.ts
- src/app/views/constants.ts
- src/app/views/detail/session/_component/database-table/detail-database-table.component.html
- src/app/views/detail/session/_component/database-table/detail-database-table.component.ts
- src/app/views/detail/session/_component/ftp-table/detail-ftp-table.component.html
- src/app/views/detail/session/_component/ftp-table/detail-ftp-table.component.ts
- src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.html
- src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.ts
- src/app/views/detail/session/_component/rest-table/detail-rest-table.component.html
- src/app/views/detail/session/_component/rest-table/detail-rest-table.component.ts
- src/app/views/detail/session/_component/smtp-table/detail-smtp-table.component.html
- src/app/views/detail/session/_component/smtp-table/detail-smtp-table.component.ts
- src/app/views/detail/session/_component/timeline/detail-timeline.component.ts
- src/app/views/search/request/search-request.view.ts
> 157 http request view

- src/app/app.component.html
- src/app/model/conf.model.ts
- src/app/shared/_component/advanced-filter/advanced-filter-modal/advanced-filter-modal.component.ts
- src/app/shared/_component/advanced-filter/advanced-filter-trigger/advanced-filter-trigger.component.ts
- src/app/views/constants.ts
- src/app/views/detail/session/_component/database-table/detail-database-table.component.html
- src/app/views/detail/session/_component/database-table/detail-database-table.component.ts
- src/app/views/detail/session/_component/ftp-table/detail-ftp-table.component.html
- src/app/views/detail/session/_component/ftp-table/detail-ftp-table.component.ts
- src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.html
- src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.ts
- src/app/views/detail/session/_component/local-table/detail-local-table.component.html
- src/app/views/detail/session/_component/local-table/detail-local-table.component.ts
- src/app/views/detail/session/_component/rest-table/detail-rest-table.component.html
- src/app/views/detail/session/_component/smtp-table/detail-smtp-table.component.html
- src/app/views/detail/session/_component/smtp-table/detail-smtp-table.component.ts
- src/app/views/search/main/search-main.view.html
- src/app/views/search/main/search-main.view.ts
- src/app/views/search/request/search-request.view.html
- src/app/views/search/rest/search-rest.view.html
- src/app/views/search/rest/search-rest.view.ts
> refactor: enhance filter functionality and update server handling in search views

- src/app/views/detail/session/_component/action-table/action-table.component.html
- src/app/views/detail/session/_component/action-table/action-table.component.scss
- src/app/views/detail/session/_component/database-table/detail-database-table.component.html
- src/app/views/detail/session/_component/database-table/detail-database-table.component.scss
- src/app/views/detail/session/_component/ftp-table/detail-ftp-table.component.html
- src/app/views/detail/session/_component/ftp-table/detail-ftp-table.component.scss
- src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.html
- src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.scss
- src/app/views/detail/session/_component/local-table/detail-local-table.component.html
- src/app/views/detail/session/_component/local-table/detail-local-table.component.scss
- src/app/views/detail/session/_component/rest-table/detail-rest-table.component.html
- src/app/views/detail/session/_component/rest-table/detail-rest-table.component.scss
- src/app/views/detail/session/_component/smtp-table/detail-smtp-table.component.html
- src/app/views/detail/session/_component/smtp-table/detail-smtp-table.component.scss
- Color and sticky header row table
> harmonisation

- src/app/service/jquery/database-request.service.ts
- src/app/service/jquery/ftp-request.service.ts
- src/app/service/jquery/ldap-request.service.ts
- src/app/service/jquery/rest-request.service.ts
- src/app/service/jquery/smtp-request.service.ts
- src/app/views/dashboard/dashboard.component.ts
close: [#218](https://github.com/oneteme/inspect-app/issues/218)
> Optimisation Request with Instance
